# Generated by Django 3.2.9 on 2021-12-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('first_name', models.CharField(help_text='Ivan', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Ivanov', max_length=50, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('make', models.CharField(blank=True, help_text='Opel', max_length=30, verbose_name='Автоконцерн')),
                ('model', models.CharField(blank=True, help_text='Corsa D', max_length=30, verbose_name='Модель')),
                ('plate_number', models.CharField(blank=True, help_text='AA 1234 OO', max_length=30, unique=True, verbose_name='Номерной знак')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='cars.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['id'],
            },
        ),
    ]
